# Generated by Django 4.0.5 on 2022-06-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание')),
                ('cities', models.CharField(max_length=150, verbose_name='Город получения')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('status', models.CharField(choices=[('Не активна', 'Не активна'), ('Активна', 'Активна')], default='Не активна', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Приз',
                'verbose_name_plural': 'Призы',
                'db_table': 'award_list',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('status', models.CharField(choices=[('Не активна', 'Не активна'), ('Активна', 'Активна')], default='Не активна', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'task_list',
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True, verbose_name='id пользователя')),
                ('tg_account', models.CharField(max_length=50, verbose_name='TG аккаунт')),
                ('full_name', models.CharField(max_length=70, verbose_name='Ф.И.О.')),
                ('change_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения баланса')),
                ('coins', models.IntegerField(default=0, verbose_name='Кол-во коинов')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'db_table': 'user_list',
                'ordering': ['-coins'],
            },
        ),
        migrations.CreateModel(
            name='CoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_account', models.CharField(max_length=50, verbose_name='TG аккаунт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание')),
                ('quantity_coins', models.IntegerField(verbose_name='Кол-во коинов')),
                ('status', models.CharField(choices=[('Обработка', 'Обработка'), ('Выполнено', 'Выполнено')], default='Обработка', max_length=20, verbose_name='Статус')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_request', to='app_coycoin.tasklist', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Заявка на получение коинов',
                'verbose_name_plural': 'Заявки на получение коинов',
                'db_table': 'coin_request',
                'ordering': ['-status'],
            },
        ),
        migrations.CreateModel(
            name='AwardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_account', models.CharField(max_length=50, verbose_name='TG аккаунт')),
                ('cities', models.CharField(max_length=50, verbose_name='Город получения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('add_information', models.TextField(verbose_name='Дополнительная информация')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('status', models.CharField(choices=[('Обработка', 'Обработка'), ('Выполнено', 'Выполнено')], default='Обработка', max_length=20, verbose_name='Статус')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_request', to='app_coycoin.awardlist', verbose_name='Приз')),
            ],
            options={
                'verbose_name': 'Заявка на получение приза',
                'verbose_name_plural': 'Заявки на получение призов',
                'db_table': 'award_request',
                'ordering': ['-status'],
            },
        ),
    ]
