# Generated by Django 4.0.5 on 2022-06-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coycoin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
