# Generated by Django 4.0.5 on 2022-06-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coycoin', '0003_awardrequest_user_id_coinrequest_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
