# Generated by Django 4.0.5 on 2022-06-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coycoin', '0004_tasklist_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardrequest',
            name='status',
            field=models.CharField(choices=[('Новый запрос', 'Новый запрос'), ('Обработка', 'Обработка'), ('Выполнено', 'Выполнено')], default='Обработка', max_length=20, verbose_name='Статус'),
        ),
    ]
